version: '3'
services:
  jd2:
    image: jd2
    container_name: jd2
    network_mode: host
    ports:
      - '3130:3130/tcp'
      - '3130:3130/udp'
      - '5800:5800/tcp'
    volumes:
      - '${VOLUME}/cfg:/opt/JDownloader/cfg'
      - '${DOWNLOADVOLUME}:/mnt/Downloads'
    environment:
      EMAIL: ${EMAIL}
      PASSWORD: ${PASSWORD}
